# Generated by Django 5.0.1 on 2024-02-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_geolocatorstats_latitude_geolocatorstats_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocatorstats',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='geolocatorstats',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
    ]
